# Generated by Django 3.1.7 on 2021-03-24 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('present_address', models.CharField(max_length=100)),
                ('permanent_address', models.CharField(max_length=100)),
                ('nid_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DrivingLicence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('l_num', models.IntegerField(verbose_name='Licence Number')),
                ('nid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='licence.nid')),
            ],
        ),
    ]
