# Generated by Django 3.1.7 on 2021-03-20 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_stuclassinfo_stushiftinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuDetailsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_section', models.CharField(max_length=20)),
                ('stu_session', models.IntegerField()),
                ('stu_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.stuclassinfo')),
                ('stu_shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.stushiftinfo')),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student')),
            ],
        ),
    ]
