# Generated by Django 3.1.7 on 2021-03-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studetailsinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(default='Address here'),
            preserve_default=False,
        ),
    ]
