# Generated by Django 3.1.7 on 2021-03-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210327_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='studetailsinfo',
            unique_together={('roll', 'stu_class', 'stu_shift', 'stu_section', 'stu_session')},
        ),
    ]
