# Generated by Django 3.1.7 on 2021-04-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
